# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /n/15/moore.1424/xillinx/axi_real_time_clock/axi_real_time_clock.cache/wt [current_project]
set_property parent.project_path /n/15/moore.1424/xillinx/axi_real_time_clock/axi_real_time_clock.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:ac701:part0:1.2 [current_project]
set_property ip_repo_paths /n/15/moore.1424/xillinx/axi_real_time_clock/axi_real_time_clock.srcs/sources_1 [current_project]
add_files -quiet /n/15/moore.1424/xillinx/axi_real_time_clock/axi_real_time_clock.runs/real_time_32b_counter_0_synth_1/real_time_32b_counter_0.dcp
set_property used_in_implementation false [get_files /n/15/moore.1424/xillinx/axi_real_time_clock/axi_real_time_clock.runs/real_time_32b_counter_0_synth_1/real_time_32b_counter_0.dcp]
add_files -quiet /n/15/moore.1424/xillinx/axi_real_time_clock/axi_real_time_clock.runs/real_time_1ms_from_125MHz_counter_0_synth_1/real_time_1ms_from_125MHz_counter_0.dcp
set_property used_in_implementation false [get_files /n/15/moore.1424/xillinx/axi_real_time_clock/axi_real_time_clock.runs/real_time_1ms_from_125MHz_counter_0_synth_1/real_time_1ms_from_125MHz_counter_0.dcp]
read_vhdl -library xil_defaultlib {
  /n/15/moore.1424/xillinx/axi_real_time_clock/axi_real_time_clock.srcs/sources_1/new/real_time_clock_64b.vhd
  /n/15/moore.1424/xillinx/axi_real_time_clock/axi_real_time_clock.srcs/sources_1/imports/xilinx/axi_template.vhd
}
synth_design -top real_time_clock_v1_0_S00_AXI -part xc7a200tfbg676-2
write_checkpoint -noxdef real_time_clock_v1_0_S00_AXI.dcp
catch { report_utilization -file real_time_clock_v1_0_S00_AXI_utilization_synth.rpt -pb real_time_clock_v1_0_S00_AXI_utilization_synth.pb }
