# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {IP_Flow 19-3664}  -suppress 
set_msg_config  -id {Synth 8-312}  -suppress 
set_msg_config  -id {Constraints 18-1079}  -suppress 
create_project -in_memory -part xc7a200tfbg676-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /n/15/moore.1424/xillinx/phase_shift_40MHz_clk_gen_axi/phase_shift_40MHz_clk_gen_axi.cache/wt [current_project]
set_property parent.project_path /n/15/moore.1424/xillinx/phase_shift_40MHz_clk_gen_axi/phase_shift_40MHz_clk_gen_axi.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:ac701:part0:1.2 [current_project]
set_property ip_repo_paths {
  /n/15/moore.1424/xillinx/ip_repo
  /n/15/moore.1424/xillinx/phase_shift_40MHz_clk_gen_axi
} [current_project]
read_vhdl -library xil_defaultlib {
  /n/15/moore.1424/xillinx/phase_shift_40MHz_clk_gen_axi/phase_shift_40MHz_clk_gen_axi.srcs/sources_1/new/clk_0_gen.vhd
  /n/15/moore.1424/xillinx/phase_shift_40MHz_clk_gen_axi/phase_shift_40MHz_clk_gen_axi.srcs/sources_1/new/clk_gen.vhd
  /n/15/moore.1424/xillinx/phase_shift_40MHz_clk_gen_axi/phase_shift_40MHz_clk_gen_axi.srcs/sources_1/imports/xilinx/phase_shift_40MHz_clk_gen.vhd
}
read_xdc /n/15/moore.1424/xillinx/phase_shift_40MHz_clk_gen_axi/phase_shift_40MHz_clk_gen_axi.srcs/constrs_1/new/phase_shift_40MHz_clk_constraints.xdc
set_property used_in_implementation false [get_files /n/15/moore.1424/xillinx/phase_shift_40MHz_clk_gen_axi/phase_shift_40MHz_clk_gen_axi.srcs/constrs_1/new/phase_shift_40MHz_clk_constraints.xdc]

synth_design -top phase_shift_40MHz_clk_gen_axi -part xc7a200tfbg676-2
write_checkpoint -noxdef phase_shift_40MHz_clk_gen_axi.dcp
catch { report_utilization -file phase_shift_40MHz_clk_gen_axi_utilization_synth.rpt -pb phase_shift_40MHz_clk_gen_axi_utilization_synth.pb }
