# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /n/15/moore.1424/xillinx/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/ip/c_counter_binary_2/c_counter_binary_2.xci
# IP: The module: 'c_counter_binary_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /n/15/moore.1424/xillinx/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/ip/c_counter_binary_2/c_counter_binary_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /n/15/moore.1424/xillinx/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/ip/c_counter_binary_2/c_counter_binary_2.xci
# IP: The module: 'c_counter_binary_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /n/15/moore.1424/xillinx/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/ip/c_counter_binary_2/c_counter_binary_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
