# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/anon/Desktop/Firmware/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/ip/prescaler_counter_binary_3/prescaler_counter_binary_3.xci
# IP: The module: 'prescaler_counter_binary_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anon/Desktop/Firmware/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/ip/prescaler_counter_binary_3/prescaler_counter_binary_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prescaler_counter_binary_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/anon/Desktop/Firmware/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/ip/prescaler_counter_binary_3/prescaler_counter_binary_3.xci
# IP: The module: 'prescaler_counter_binary_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anon/Desktop/Firmware/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/ip/prescaler_counter_binary_3/prescaler_counter_binary_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prescaler_counter_binary_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
