# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /n/15/moore.1424/xillinx/axi_real_time_clock/axi_real_time_clock.srcs/sources_1/ip/real_time_32b_counter_0/real_time_32b_counter_0.xci
# IP: The module: 'real_time_32b_counter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /n/15/moore.1424/xillinx/axi_real_time_clock/axi_real_time_clock.srcs/sources_1/ip/real_time_32b_counter_0/real_time_32b_counter_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'real_time_32b_counter_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /n/15/moore.1424/xillinx/axi_real_time_clock/axi_real_time_clock.srcs/sources_1/ip/real_time_32b_counter_0/real_time_32b_counter_0.xci
# IP: The module: 'real_time_32b_counter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /n/15/moore.1424/xillinx/axi_real_time_clock/axi_real_time_clock.srcs/sources_1/ip/real_time_32b_counter_0/real_time_32b_counter_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'real_time_32b_counter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
