# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /n/15/moore.1424/xillinx/pulse_gen_axi/pulse_gen_axi.srcs/sources_1/ip/pulse_gen_32b_counter/pulse_gen_32b_counter.xci
# IP: The module: 'pulse_gen_32b_counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /n/15/moore.1424/xillinx/pulse_gen_axi/pulse_gen_axi.srcs/sources_1/ip/pulse_gen_32b_counter/pulse_gen_32b_counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pulse_gen_32b_counter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /n/15/moore.1424/xillinx/pulse_gen_axi/pulse_gen_axi.srcs/sources_1/ip/pulse_gen_32b_counter/pulse_gen_32b_counter.xci
# IP: The module: 'pulse_gen_32b_counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /n/15/moore.1424/xillinx/pulse_gen_axi/pulse_gen_axi.srcs/sources_1/ip/pulse_gen_32b_counter/pulse_gen_32b_counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pulse_gen_32b_counter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
