# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.cache/wt [current_project]
set_property parent.project_path /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:ac701:part0:1.2 [current_project]
set_property ip_repo_paths {
  /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.srcs
  /home/anon/Desktop/FirmwareNEU/repo_projects/ip_repo/myip_1.0
} [current_project]
add_files -quiet /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.runs/blk_mem_gen_1_synth_1/blk_mem_gen_1.dcp
set_property used_in_implementation false [get_files /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.runs/blk_mem_gen_1_synth_1/blk_mem_gen_1.dcp]
add_files -quiet /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.runs/c_counter_binary_1_synth_1/c_counter_binary_1.dcp
set_property used_in_implementation false [get_files /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.runs/c_counter_binary_1_synth_1/c_counter_binary_1.dcp]
add_files -quiet /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.runs/c_counter_binary_2_synth_1/c_counter_binary_2.dcp
set_property used_in_implementation false [get_files /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.runs/c_counter_binary_2_synth_1/c_counter_binary_2.dcp]
add_files -quiet /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.runs/prescaler_counter_binary_3_synth_1/prescaler_counter_binary_3.dcp
set_property used_in_implementation false [get_files /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.runs/prescaler_counter_binary_3_synth_1/prescaler_counter_binary_3.dcp]
read_vhdl -library xil_defaultlib {
  /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/new/riseing_edge_persist.vhd
  /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/imports/moore.1424/xillinx/trigger_logic_ac701/trigger_logic_ac701.srcs/sources_1/new/add_module.vhd
  /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/imports/new/lib.vhd
  /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/imports/moore.1424/xillinx/trigger_logic_ac701/trigger_logic_ac701.srcs/sources_1/new/handshake_unit.vhd
  /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/imports/moore.1424/xillinx/trigger_logic_ac701/trigger_logic_ac701.srcs/sources_1/new/coincidence_unit.vhd
  /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/new/pulse_gen.vhd
  /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/new/prescaler.vhd
  /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/imports/moore.1424/xillinx/trigger_logic_ac701/trigger_logic_ac701.srcs/sources_1/new/one_ch_delay.vhd
  /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/imports/moore.1424/xillinx/trigger_logic_ac701/trigger_logic_ac701.srcs/sources_1/new/beam_current_monitor.vhd
  /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/imports/moore.1424/xillinx/trigger_logic_ac701/trigger_logic_ac701.srcs/sources_1/new/tlu_frontend.vhd
  /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/imports/moore.1424/xillinx/trigger_logic_ac701/trigger_logic_ac701.srcs/sources_1/new/tlu_backend.vhd
  /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.srcs/sources_1/new/trigger_logic_axi.vhd
}
read_xdc /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.srcs/constrs_1/imports/new/ac701_trigger_logic_design.xdc
set_property used_in_implementation false [get_files /home/anon/Desktop/FirmwareNEU/repo_projects/trigger_logic_axi_io/trigger_logic_axi_io.srcs/constrs_1/imports/new/ac701_trigger_logic_design.xdc]

synth_design -top trigger_logic_AXI -part xc7a200tfbg676-2
write_checkpoint -noxdef trigger_logic_AXI.dcp
catch { report_utilization -file trigger_logic_AXI_utilization_synth.rpt -pb trigger_logic_AXI_utilization_synth.pb }
